import React from 'react'

export const metadata = {
  title: "Stay Options",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <div>
      stay
    </div>
  )
}
